// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"billing3/database/types"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Category struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Gateway struct {
	ID          int32                 `json:"id"`
	DisplayName string                `json:"display_name"`
	Name        string                `json:"name"`
	Settings    types.GatewaySettings `json:"settings"`
	Enabled     bool                  `json:"enabled"`
	Fee         pgtype.Text           `json:"fee"`
}

type Invoice struct {
	ID                 int32           `json:"id"`
	UserID             int32           `json:"user_id"`
	Status             string          `json:"status"`
	CancellationReason pgtype.Text     `json:"cancellation_reason"`
	PaidAt             types.Timestamp `json:"paid_at"`
	DueAt              types.Timestamp `json:"due_at"`
	Amount             decimal.Decimal `json:"amount"`
	CreatedAt          types.Timestamp `json:"created_at"`
}

type InvoiceItem struct {
	ID          int32           `json:"id"`
	InvoiceID   int32           `json:"invoice_id"`
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
	Type        string          `json:"type"`
	ItemID      pgtype.Int4     `json:"item_id"`
	CreatedAt   types.Timestamp `json:"created_at"`
}

type InvoicePayment struct {
	ID          int32           `json:"id"`
	InvoiceID   int32           `json:"invoice_id"`
	CreatedAt   types.Timestamp `json:"created_at"`
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
	ReferenceID string          `json:"reference_id"`
	Gateway     string          `json:"gateway"`
}

type Product struct {
	ID           int32                 `json:"id"`
	Name         string                `json:"name"`
	Description  string                `json:"description"`
	CategoryID   int32                 `json:"category_id"`
	Extension    string                `json:"extension"`
	Enabled      bool                  `json:"enabled"`
	Pricing      types.ProductPrices   `json:"pricing"`
	Settings     types.ProductSettings `json:"settings"`
	Stock        int32                 `json:"stock"`
	StockControl int32                 `json:"stock_control"`
}

type ProductOption struct {
	ProductID   int32                     `json:"product_id"`
	Name        string                    `json:"name"`
	DisplayName string                    `json:"display_name"`
	Type        string                    `json:"type"`
	Regex       string                    `json:"regex"`
	Values      types.ProductOptionValues `json:"values"`
	Description string                    `json:"description"`
}

type Server struct {
	ID        int32                `json:"id"`
	Label     string               `json:"label"`
	Extension string               `json:"extension"`
	Settings  types.ServerSettings `json:"settings"`
}

type Service struct {
	ID                 int32                 `json:"id"`
	Label              string                `json:"label"`
	UserID             int32                 `json:"user_id"`
	Status             string                `json:"status"`
	CancellationReason pgtype.Text           `json:"cancellation_reason"`
	BillingCycle       int32                 `json:"billing_cycle"`
	Price              decimal.Decimal       `json:"price"`
	Extension          string                `json:"extension"`
	Settings           types.ServiceSettings `json:"settings"`
	ExpiresAt          types.Timestamp       `json:"expires_at"`
	CreatedAt          types.Timestamp       `json:"created_at"`
	CancelledAt        types.Timestamp       `json:"cancelled_at"`
}

type Session struct {
	ID        int32           `json:"id"`
	Token     string          `json:"token"`
	UserID    int32           `json:"user_id"`
	CreatedAt types.Timestamp `json:"created_at"`
	ExpiresAt types.Timestamp `json:"expires_at"`
}

type User struct {
	ID       int32       `json:"id"`
	Email    string      `json:"email"`
	Name     string      `json:"name"`
	Role     string      `json:"role"`
	Password string      `json:"-"`
	Address  pgtype.Text `json:"address"`
	City     pgtype.Text `json:"city"`
	State    pgtype.Text `json:"state"`
	Country  pgtype.Text `json:"country"`
	ZipCode  pgtype.Text `json:"zip_code"`
}
